#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 5000
#define MAX_PLAYERS 4

#define BUFFER_SIZE 8192
#define COMMAND_SIZE 256

#define CLIENT_ROLE "PLAYER"
#define TEMP_PLAYER_ID 1

#define OPTION_PING 1
#define OPTION_MOVE_LEFT 2
#define OPTION_MOVE_RIGHT 3
#define OPTION_SHOOT 4
#define OPTION_TICK 5
#define OPTION_SEND_CUSTOM_MESSAGE 6
#define OPTION_DISCONNECT 7

#define MAX_ALIENS 128
#define MAX_PROJECTILES 128
#define MAX_BUNKERS 16
#define MAX_UFOS 8

#define WORLD_WIDTH 100
#define WORLD_HEIGHT 100

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 700

#define GAME_AREA_X 40
#define GAME_AREA_Y 90
#define GAME_AREA_WIDTH 920
#define GAME_AREA_HEIGHT 560

#endif