#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 5000

#define BUFFER_SIZE 1024
#define COMMAND_SIZE 256

#define CLIENT_ROLE "PLAYER"
#define TEMP_PLAYER_ID 1

#define OPTION_PING 1
#define OPTION_MOVE_LEFT 2
#define OPTION_MOVE_RIGHT 3
#define OPTION_SHOOT 4
#define OPTION_SEND_CUSTOM_MESSAGE 5
#define OPTION_DISCONNECT 6

#endif